version : '3'
services:
  library:
    buiild: ./LibrarySpringBoot
    ports:
    - "8080:8000"
    depends_on:
      - database
  localhost:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: libraryuser
      POSTGRES_DB: libraryBase
    ports:
    - "5432:5432"
