version : '3.4'
services:
  library:
    image: libobraz:v1
    volumes:
      - /volumenLoc:/volumenCon
    ports:
    - "8000:8080"
    container_name: library
    deploy:
      mode: global
    depends_on:
      - database
  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: libraryuser
      POSTGRES_DB: libraryBase
    ports:
    - "1000:5432"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s
